import json
from typing import Any

from avala.common.clock import get_game_ends_at_tick, get_tick_number
from sqlalchemy import case, distinct, func, select

from server.database import Database, StateManager

from ..flags.models import Flag

# AI WARNING & TODO: Large chunks of this code are generated by AI. Review and test thoroughly before ECSC2025.


async def get_flag_ids(db: Database) -> dict | None:
    """
    Loads the flag IDs from the database.
    """
    async with StateManager(db) as state:
        flag_ids = await state.get("flag_ids")
        return json.loads(flag_ids) if flag_ids else None


async def get_target_hosts(db: Database) -> set[str]:
    """
    Retrieve the set of target hosts from the database.
    """
    flag_ids = await get_flag_ids(db)
    if not flag_ids:
        return set()

    return {host for service_data in flag_ids.values() for host in service_data.keys()}


async def get_target_services(db: Database) -> set[str]:
    """
    Retrieve the set of target services from the database.
    """
    flag_ids = await get_flag_ids(db)
    if not flag_ids:
        return set()

    return set(flag_ids.keys())


async def get_distinct_exploits(db: Database) -> set[str]:
    """
    Retrieve the set of distinct exploits from the database.
    """
    query = select(Flag.exploit).distinct()
    result = await db.execute(query)
    return {exploit for exploit in result.scalars() if exploit is not None}


async def count_flags_by_status_and_tick_range(
    db: Database,
    status: str,
    after_tick: int | None = None,
    before_tick: int | None = None,
) -> int:
    """
    Count the number of flags in the database based on their status and tick range. Tick numbers are inclusive.
    """
    query = select(func.count(Flag.id)).filter(Flag.status == status)

    if after_tick is not None:
        query = query.filter(Flag.tick >= after_tick)
    if before_tick is not None:
        query = query.filter(Flag.tick <= before_tick)

    result = await db.execute(query)
    count = result.scalar_one()

    return count


async def compute_tick_graph(
    db: Database,
    status: str | None = None,
    exploit: str | None = None,
) -> list[int]:
    """
    Compute tick flag graph for flags with the given status and exploit.
    """
    total_ticks = get_game_ends_at_tick()

    query = select(Flag.tick, func.count(Flag.id)).group_by(Flag.tick).order_by(Flag.tick)

    if status is not None:
        query = query.filter(Flag.status == status)
    if exploit is not None:
        query = query.filter(Flag.exploit == exploit)

    result = await db.execute(query)
    tick_counts: dict[int, int] = dict(result.all())
    return [tick_counts.get(tick, 0) for tick in range(total_ticks)]


async def compute_attack_heatmap(
    db: Database,
    status: str | None = None,
    exploit: str | None = None,
    last_n_ticks: int | None = None,
) -> list[list[int]]:
    """
    Compute the attack heatmap for flags with the given status and exploit.
    """
    hosts = sorted(await get_target_hosts(db))
    services = sorted(await get_target_services(db))

    current_tick = get_tick_number()

    query = select(Flag.host, Flag.service, func.count(Flag.id)).group_by(Flag.host, Flag.service)

    if status is not None:
        query = query.filter(Flag.status == status)
    if exploit is not None:
        query = query.filter(Flag.exploit == exploit)

    if last_n_ticks is not None:
        start_tick = current_tick - last_n_ticks
        query = query.filter(Flag.tick >= start_tick, Flag.tick <= current_tick)

    result = await db.execute(query)

    counts_map = {(row.host, row.service): row[2] for row in result}  # row[2] is the count

    heatmap_matrix: list[list[int]] = []

    for host in hosts:
        row_values: list[int] = []
        for service in services:
            count = counts_map.get((host, service), 0)
            row_values.append(count)
        heatmap_matrix.append(row_values)

    return heatmap_matrix


async def fetch_exploit_data(
    db: Database,
):
    current_tick = get_tick_number()

    all_exploits = (await db.execute(select(Flag.exploit).distinct().filter(Flag.exploit.isnot(None)))).scalars().all()

    if not all_exploits:
        return []

    exploit_data_map: dict[str, dict[str, Any]] = {
        exploit: {
            "exploit_name": exploit,
            "unique_hosts_current_tick": 0,
            "flags_queued_current_tick": 0,
            "flags_accepted_current_tick": 0,
            "flags_rejected_current_tick": 0,
            "flags_accepted_last_10_ticks": [0] * 10,
        }
        for exploit in all_exploits
    }

    current_tick_metrics_query = (
        select(
            Flag.exploit,
            func.count(distinct(Flag.host)),
            func.sum(case((Flag.status == "queued", 1), else_=0)),
            func.sum(case((Flag.status == "accepted", 1), else_=0)),
            func.sum(case((Flag.status == "rejected", 1), else_=0)),
        )
        .filter(Flag.tick == current_tick, Flag.exploit.isnot(None))
        .group_by(Flag.exploit)
    )

    current_tick_metrics_result = await db.execute(current_tick_metrics_query)
    for exploit, unique_hosts, queued, accepted, rejected in current_tick_metrics_result:
        if exploit in exploit_data_map:
            exploit_data_map[exploit]["unique_hosts_current_tick"] = unique_hosts
            exploit_data_map[exploit]["flags_queued_current_tick"] = queued
            exploit_data_map[exploit]["flags_accepted_current_tick"] = accepted
            exploit_data_map[exploit]["flags_rejected_current_tick"] = rejected

    start_tick_for_10 = max(0, current_tick - 9)

    last_10_ticks_accepted_query = (
        select(Flag.exploit, Flag.tick, func.count(Flag.id))
        .filter(
            Flag.status == "accepted",
            Flag.exploit.isnot(None),
            Flag.tick >= start_tick_for_10,
            Flag.tick <= current_tick,
        )
        .group_by(Flag.exploit, Flag.tick)
        .order_by(Flag.exploit, Flag.tick)
    )

    last_10_ticks_accepted_result = await db.execute(last_10_ticks_accepted_query)

    temp_accepted_counts: dict[str, dict[int, int]] = {}
    for exploit, tick, count in last_10_ticks_accepted_result:
        if exploit not in temp_accepted_counts:
            temp_accepted_counts[exploit] = {}
        temp_accepted_counts[exploit][tick] = count

    for exploit in all_exploits:
        if exploit in exploit_data_map:
            accepted_list = [0] * 10
            for i in range(10):
                tick_to_check = current_tick - (9 - i)
                if tick_to_check >= 0:
                    accepted_list[i] = temp_accepted_counts.get(exploit, {}).get(tick_to_check, 0)
            exploit_data_map[exploit]["flags_accepted_last_10_ticks"] = accepted_list

    exploit_data_list = list(exploit_data_map.values())

    return exploit_data_list
