[project]
name = "avala-shared"
version = "0.1.0"
description = "Shared functions used in both avala-server and avala-client"
authors = [
    {name = "Dušan Lazić", email = "lazicdusan@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.2",
    "pytz>=2024.2",
    "tzlocal>=5.2",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "ruff>=0.8.1",
    "types-pytz>=2024.2.0.20241003",
]

[tool.ruff.lint]
select = ["I"]

[tool.isort]
include_trailing_comma = true
