site_name: ""
site_url: https://avala.lazicdusan.com
repo_url: https://github.com/dusanlazic/avala
repo_name: dusanlazic/avala
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tabs
  palette:
    scheme: slate
    primary: black
    accent: red
markdown_extensions:
- attr_list
- md_in_html
- def_list
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.tabbed:
    alternate_style: true 
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- toc:
    permalink: true
extra_css:
  - stylesheets/extra.css

nav:
  - Server setup:
      - Overview: server/index.md
      - Writing submitter script: server/submitter.md
      - Writing flag IDs script: server/flag-ids.md
      - Configuration: server/configuration.md
      - Launching: server/launching.md
  - Exploit development:
      - Overview: client/index.md
      - Client setup: client/setup.md
      - Decorator options: client/decorator.md
      - Storage: client/storage.md
      - Usage examples: client/examples.md
      - Avala class: client/avala-class.md
  - Attack monitoring:
      - Overview: dashboard/index.md
  - Infrastructure tips:
      - Overview: infrastructure/index.md
  - Troubleshooting:
      - Overview: troubleshooting/index.md
  - Contributing:
      - Overview: contributing/index.md
